image: "openjdk:latest"

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - ".gradle/caches"

before_script:
  - "export GRADLE_USER_HOME=$(pwd)/.gradle"
  - "chmod +x ./gradlew"

stages:
  - "build"
  - "test"

build:
  stage: "build"
  script:
    - "./gradlew build"
  except:
    - "tags"

test:
  stage: "test"
  script:
    - "./gradlew check --stacktrace"
  artifacts:
    paths:
      - "*/build/test-results/**/TEST-*.xml"
      - "*/build/reports/*.xml"
    reports:
      junit:
        - "*/build/test-results/**/TEST-*.xml"
        - "*/build/reports/*.xml"
  except:
    - "tags"
